### ISSUE TITLE
SyntaxError thrown during instalation with pip

### ISSUE THREAD

**Issue by samuelmovi** [bodylabs/drf-to-s3#9]
After executing `pip install drf_to_s3`, I get the following:

```
Collecting drf_to_s3
  Using cached drf_to_s3-0.7.7.tar.gz (15 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/sam/py3venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_8m5mejn/drf-to-s3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_8m5mejn/drf-to-s3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-f8wxr7d9
         cwd: /tmp/pip-install-_8m5mejn/drf-to-s3/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_8m5mejn/drf-to-s3/setup.py", line 9
        print 'warning: pandoc or pypandoc does not seem to be installed; using empty long_description'
                                                                                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('warning: pandoc or pypandoc does not seem to be installed)?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Could it be there's a missing parenthesis? I guess not, but something else prior might  be causing that.
Thankx

**Comment by paulmelnikow** [comment]
Looks like this needs to be updated for Python 3. A pull request would be welcome!

**Comment by paulmelnikow** [comment]
There may be quite a lot in the project that needs updating. If anyone is using this with current Python or current versions of dependencies, indeed I'd be happy to accept a pull request!
